# Generated by Django 2.0 on 2018-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180110_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.IntegerField(),
        ),
    ]
